language: go

go:
  - 1.9

install:
  - make

script:
  - make test
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - make VERSION="${TRAVIS_TAG:-latest}" dist

before_deploy:
# Set up git user name and tag this commit
  - git config --local user.name "mtilson"
  - git config --local user.email "m@tilson.biz"
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
    - ts-gotpl-alpine-linux-amd64-*.tar.gz
    - ts-gotpl-linux-amd64-*.tar.gz
    - ts-gotpl-linux-i386-*.tar.gz
    - ts-gotpl-linux-armel-*.tar.gz
    - ts-gotpl-linux-armhf-*.tar.gz
    - ts-gotpl-darwin-amd64-*.tar.gz
    - ts-gotpl-darwin-i386-*.tar.gz
  on:
    tags: true

notifications:
  email:
    on_success: never
