language: go

go:
  - 1.6

install:
  - make

script:
  - make test
  - make VERSION="${TRAVIS_TAG:-latest}" dist

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  overwrite: true
  skip_cleanup: true
  file_glob: true
  file:
    - ts-gotpl-alpine-linux-amd64-*.tar.gz
    - ts-gotpl-linux-amd64-*.tar.gz
    - ts-gotpl-linux-i386-*.tar.gz
    - ts-gotpl-linux-armel-*.tar.gz
    - ts-gotpl-linux-armhf-*.tar.gz
    - ts-gotpl-darwin-amd64-*.tar.gz
    - ts-gotpl-darwin-i386-*.tar.gz
  on:
    tags: true

notifications:
  email:
    on_success: never
